// examples/vue/src/components/ImageZoom.vue
<script setup lang="ts">
import {  watch, type ImgHTMLAttributes, type ComponentPublicInstance } from 'vue'
import mediumZoom, { type Zoom, type ZoomOptions } from 'medium-zoom'

interface Props extends ImgHTMLAttributes {
  options?: ZoomOptions
}

const props = defineProps<Props>()

let zoom: Zoom | null = null

function getZoom() {
  if (zoom === null) {
    zoom = mediumZoom(props.options)
  }

  return zoom
}

function attachZoom(ref: Element | ComponentPublicInstance | null) {
  const image = ref as HTMLImageElement | null
  const zoom = getZoom()

  if (image) {
    zoom.attach(image)
  } else {
    zoom.detach()
  }
}

watch(() => props.options, (options) => {
  const zoom = getZoom()
  zoom.update(options || {})
})
</script>

<template>
  <img :ref="attachZoom" />
</template>

// examples/svelte/src/lib/ImageZoom.svelte
<script>
  import mediumZoom from 'medium-zoom'

  export let src = undefined
  export let alt = undefined
  export let options = undefined

  let zoom = null

  function getZoom() {
    if (zoom === null) {
      zoom = mediumZoom(options)
    }

    return zoom
  }

  function attachZoom(image) {
    const zoom = getZoom()
    zoom.attach(image)

    return {
      update(newOptions) {
        zoom.update(newOptions)
      },
      destroy() {
        zoom.detach()
      },
    }
  }
</script>

<img {src} {alt} {...$$restProps} use:attachZoom={options} />
